tii1q_b1.py, tii1q_b1.yml
New calibrated runcard for tii1q_b1 with the rfsoc4x2
=> RFSoC4x2 (runcard tiii1q_b1)

iqm5q.yml, qw25q.yml, qw5q_gold.yml, tii1q_b1.yml, tii_zcu111.yml
This PR adds the Ec, Ej, g and assigment fidelity to the qubit runcards. These attributes are needed in qibocal for flux flux routines fitting (david/flux_routines_fitting).
Assigment fidelity needed for a webapp tool that I have implemented that shows the qpus/qubits status and latest characterization
@scarrazza could we merge this PR as soon as possible. Tests in qibocal PR 437 (https://github.com/qiboteam/qibocal/pull/437) are not passing because we need these attributes.
=> adding qubit attributes needed for flux routines fitting

qw5q_gold.yml, qw5q_gold_qblox.py
Initial recalibration of the runcard for qw5q_gold.
Currently I get the following assignment fidelities:
- q0: 0.894
- q1: 0.91
- q2: 0.906
- q3: 0.922
- q4: 0.853
Here is the qibocal report: http://login.qrccluster.com:9000/kjZBiKVbSr2sSVuynp8Ynw==/
I didn't try to run anything related to two qubit gates yet with this runcard.
=> Recalibration after power outage

.github/workflows/rules.yml, iqm5q.py, tests/test_platforms.py
Fixes #44 by adding a simple CI that checks creation of all platforms. The environment and Python version used is matching the `qibo` module in the cluster, to make sure that all platforms here are compatible.
=> Test platform creation

.github/workflows/main.yml, .github/workflows/stable.yml, iqm5q.py, iqm5q.yml, iqm5q_q0.py, iqm5q_q0.yml, qw5q_gold.yml, qw5q_gold_qblox.py, tii1q_b4_qblox.py, tii1q_b4_qblox.yml, tii_zcu111.py, tii_zcu111.yml, tii_zcu216.py, tii_zcu216.yml
Updates runcards for the new layout implemented in qiboteam/qibolab#585. I would like to wait for qiboteam/qibolab#508 before merging this, because a few more changes may be required in the interface.
I also added a workflow that is running the platform creation test with qibolab main. We can use this to check if the runcards are compatible with main before releasing qibolab. @AleCandido can you help me on how to properly activate the poetry environment in that workflow
https://github.com/qiboteam/qibolab_platforms_qrc/blob/1d0e89d00ce159d5c9fad12bb500721113aa5047/.github/workflows/main.yml#L30
=> Add instruments section in runcards

iqm5q.yml, qw5q_gold.yml
Same as qiboteam/qibolab#613.
Now as expected tests with the qibolab latest are passing and qibolab stable are not passing anymore.
If you want both tests to pass we could eventually remove temporarily `assignment_fidelity` from the runcard.
=> Fixing `assignment_fidelity` typo

iqm5q.yml
Improves assignment fidelity from 51% to 84% (blobs are still gaussian).
=> Updated sweetspot for qubit 0

iqm5q.py
LabOne Q 2.19 [introduced builder API](https://docs.zhinst.com/labone_q_user_manual/release_notes/#release-2190) for constructing `DeviceSetup` objects at runtime as an alternative to YAML based descriptors. This PR replaces the runtime YAML string assembly present in ZI based platform files.
Since this feature requires LabOne Q 2.19, the dependencies in the related projects should be updated as well.
Currently, this is in draft state. Before merging this,`Zurich` constructor should be modified to consume a `DeviceSetup` instead of a descriptor yaml file.
=> Use device setup builder api when creating `Zurich` instance

iqm5q.py
Required for compatibility with qibolab main after merging qiboteam/qibolab#666.
=> Fix local oscillator import for iqm5q

iqm5q.py, tii1q_b1.py, tii_zcu111.py, tii_zcu216.py
In qiboteam/qibolab#739 I removed `Controller.__getitem__` and left only `Controller.ports` to access the ports for consistency, particularly because for some instruments `.ports` has more than one arguments.
=> Use `controller.ports`

qw5q_platinum/parameters.json
Trying to reduce readout time in order to improve the now limited by coherence times QND measure.
q0: 
High resonator depletion time (4.5us) The allxy results is already decaying due to coherence times.
http://login.qrccluster.com:9000/MHuZP_4OTa-U-6JWFFCf4Q==
np.exp(-t_sequence/T1) [t_sequence = 2 readouts + depletion] gives a max fidelity of 0.818 for the T1 value around 40 us. I will suggest not to use this qubit restlessly until we can deplete the resonator faster.
q2:
Lower resonator depletion time (2us)
http://login.qrccluster.com:9000/wvOYGOkqS0-cV5JTQzxYZw==
Shorter readout (QND = 0.91)
http://login.qrccluster.com:9000/V_XRXA70R56OiCNmQK1EQg==/
q3: Uncalibrated qubit (pi-pulse not working)
=> Shorter readout for qwq5 platinum

qw5q_platinum/platform.py
Different qubits might need different powers in both flux and drive. 
I have unrolled what was previously a `for` loop. 
I have put as placeholders the latest needs from calibration from @biankawolo .
=> Unrolling the qubit power and flux setters

qw11q/parameters.json
To test https://github.com/qiboteam/qibolab/pull/980 and to avoid errors when executing circuits.
=> Remove uncalibrated thresholds from qw11q

qw11q/parameters.json
I manage to recalibrate only qubits [`D1`](http://login.qrccluster.com:9000/ZZTsob4YQ4utJIycz0q-vg==/), [`D2`](http://login.qrccluster.com:9000/hwpGejQ5RYOJSGA4T9Avug==/) and [`D3`](http://login.qrccluster.com:9000/IhhxbKARRm-sAnUlvJy5MA==/).
Qubit `D4` seems to be out of reach with the latest shifts.
=> Sweetspot recalibration for qw11q

qw11q/parameters.json
Same as #171 following unexpected instruments disconnection.
The addressable qubits are still [D1](http://login.qrccluster.com:9000/8TSm3oGCTPSpD1SVfzmTRQ==), [D2](http://login.qrccluster.com:9000/3RFsR1U9T1ucsE9R1S6uEg==) and [D3](http://login.qrccluster.com:9000/iC14ZNuhReKZzvptb1VH6w==).
=> Sweetspot recalibration of qw11q

qw11q/parameters.json
Sweetspot recalibration for [D1](http://login.qrccluster.com:9000/6M7lmyJhRpGaIn681nyaDg==), [D2](http://login.qrccluster.com:9000/lZq7gzXNS-uNPwk7GjvZZg==) and [D3](http://login.qrccluster.com:9000/P0sj2j9FTqy7MulpipmzUw==).
By increasing the drive power now I've been able to address also [D5](http://login.qrccluster.com:9000/nxoGZJ_1SWuKY-cHzgif5A==). Despite achieving 98% readout fidelity T2 looks weird.
=> Sweetspot recalibration after disconnection

qw11qD/parameters.json, qw11qD/platform.py
https://github.com/qiboteam/qibolab/pull/1001
=> Update QM for new qubits/channels

qw5q_platinum/parameters.json, qw5q_platinum/platform.py
Requires https://github.com/qiboteam/qibolab/pull/1068. Updated qibocal routines have been tested to work: http://login.qrccluster.com:9000/f5mxayd_QXOwM9TcgpvEBw==.
=> qw5q_platinum controlled with QM OPX1000 for qibolab 0.2

qw5q_platinum/calibration_db.json, qw5q_platinum/parameters.json, qw5q_platinum/platform.py
Needs https://github.com/qiboteam/qibolab/pull/1045 to work.
I will add some reports once I manage to calibrate in a bit more detail.
=> qw5q_platinum using QM OPX1000

qw11q/parameters.json
Qubit | T1 (us) | T2 (us) | Assignment Fidelity | Gate infidelity (1e-3) |
-- | -- | -- | -- | -- 
B2 | 20 | 12 | 97% | 2.00 (0.02)
B3 | 24 | 21 | 94% | 1.61 (0.02)
B5 | 34 | 28 | 95% | 0.61 (0.03)
* Single shot: http://login.qrccluster.com:9000/V4wiVyGyTy2D5y394Q4mXw==
* Rabi amplitude: http://login.qrccluster.com:9000/sTG9-BnIRVS1QxSJd_RPqQ==
* T1: http://login.qrccluster.com:9000/8S6hIAl4Q0OqD8dlzc00SA==
* T2 B2: http://login.qrccluster.com:9000/KMN4NjxMQP2byzlSKd6QDQ==
* T2 B3: http://login.qrccluster.com:9000/5U0NfVToQti_SW-gR87KKg==
* T2 B5: http://login.qrccluster.com:9000/rbmarqg4TAmNSaF_tdFtTw==
* RB B2: http://login.qrccluster.com:9000/Dutn72szTrabOQsCSzgWLA==
* RB B3: http://login.qrccluster.com:9000/skFVeQiTSIWKWFDKcJEC4g==
* RB B5: …
=> Recalibration of line B of qw11q

convert.py, qw11q/connections.json, qw5q_platinum/connections.json
In 0.1 the parameters of QM configs were stored as instrument settings, therefore we need a mapping between the 0.2 channels and 0.1 instrument ports. I added this in a new `connections.json` file to avoid making the upgrader dependable on qibolab versions.
Now the usage should be
```sh
python convert.py qw11q/parameters.json --connections qw11q/connections.json
```
in order to include the QM configs in the new parameters.
I have provided `connections.json` for qw11q and qw5q_platinum.
=> Support QM specific configs in the 0.2 platform upgrader

convert.py
Needed to port the latest qw5q_platinum calibration to 0.2, because it is using the `Exponential` shape.
=> Support exponential shape in convert.py

qw11q/parameters.json
On the qw11q the lab installed a different TWPA which operates at a much lower power. As a safety feature I suggest to reduce the power to avoid possible damage of the twpa. Note that at the moment the TWPA is not calibrated and the purpose of this is to avoid any potential harm to the twpa.
=> TWPA power - reduced - URGENT

.github/workflows/tests.yml
After the refactoring of dependencies in qibolab.
Note that this will only work for QM, as we have not created the qibolab-* repositories for other drivers. I also had to install `qcodes` manually, as it is needed to instantiate the R&S LOs used as TWPA pumps. I am not sure if there is a more elegant solution,
=> Add missing dependencies in CI

iqm5q/calibration.json, iqm5q/parameters.json, iqm5q/platform.py
Only single qubit gates for qubit 0 are calibrated! Here are some reports from yesterday:
* Qubit spectroscopy: http://login.qrccluster.com:9000/9uYo0rRUSee1r0GJCqdkoA==
* Dispersive shift: http://login.qrccluster.com:9000/BDhqJNoMSJGhPBIc94FnSg==
* Single shot: http://login.qrccluster.com:9000/r8X-7Q-7R-q4qUaZfNol3g==
* Rabi: http://login.qrccluster.com:9000/kQbNm1Z-R-qzWqffM2BPOA==
Circuits and routines without sweepers should work with qibolab 0.2.8. Routines with sweepers need some fixes from https://github.com/qiboteam/qibolab/pull/1252.
=> iqm5q controlled with Qblox (only qubit 0)
